(** Warning generated by static analazyer. *)
type warn_ty =
  | Inspection
  | InternalError
[@@deriving yojson]

(** How likely a warning points at a real problem. *)
type severity = Low | Medium | High

val severity_to_string : severity -> string
val severity_of_string : string -> severity option

val severity_rank : severity -> int
(** [severity_rank] orders severities from [Low] to [High]. *)

type t = {
  linenr: int;
  column: int;
  file: string;
  id: string;
  msg: string;
  context: string;
  ty: warn_ty [@key "type"];
  severity: severity;
} [@@deriving yojson]

val mk : ?ty:(warn_ty) -> ?file:(string) -> ?context:(string) -> ?severity:(severity) -> int -> int -> string -> string -> t
val mk_internal : ?id:(string) -> string -> t
val mk_from_lexbuf : ?context:(string) -> Lexing.lexbuf -> string -> string -> t

val to_string : t -> string
